name: Build & Upload SBOM to Aqua

on: [push, pull_request]

jobs:
  build-and-upload:
    name: Build & Aqua SBOM Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Maven project
        run: mvn clean package

      - name: Install Billy CLI
        run: |
          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
          chmod +x install.sh
          BINDIR="." sh install.sh

      - name: Scan with Billy (generate + upload SBOM)
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./billy scan \
            --access-token "${GITHUB_TOKEN}" \
            --aqua-key "${AQUA_KEY}" \
            --aqua-secret "${AQUA_SECRET}" \
            --artifact-path target/*.jar \
            --sbom-path sbom.json \
            --log-file billy.log \
            --cspm-url https://eu-1.api.cloudsploit.com
