name: Build & Upload SBOM to Aqua

on: [push, pull_request]

jobs:
  build-and-upload:
    name: Build & Aqua SBOM Upload
    runs-on: ubuntu-latest  # works only if runner has access to Aqua's download endpoint

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Maven project
        run: mvn clean package

      - name: Install Legacy Billy CLI
        run: |
          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
          chmod +x install.sh
          BINDIR="." sh install.sh
          echo "Installed Billy CLI"

      - name: Generate SBOM from JAR (Legacy)
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
          TRIVY_DB_REPOSITORY: "registry.aquasec.com/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "registry.aquasec.com/trivy-java-db:1"
          TRIVY_CHECKS_BUNDLE_REPOSITORY: "registry.aquasec.com/trivy-checks:1"
          TRIVY_QUIET: true
          BILLY_SERVER: https://billy.codesec.aquasec.com
        run: |
          ./billy generate \
            --input target/*.jar \
            --output sbom.json

      - name: Upload SBOM to Aqua (Legacy)
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
        run: |
          ./billy upload \
            --sbom sbom.json \
            --aqua-key "${AQUA_KEY}" \
            --aqua-secret "${AQUA_SECRET}"
